### ISSUE TITLE
Lab upload with lookup table and regex

### ISSUE THREAD

**Issue by philippkraft** [jlu-ilr-hydro/odmf#85]
Replaces #9 

Use an additional file to parse sample names into dates / sites

- [ ] a) Link an external sample mapping yaml-file in a .conf file
- [ ] b) Write a sample parser to deduce site, date, etc from a sample name
- [ ] c) Find the most actual dataset from sample name (site), instument (conf file main section) and valuetype (conf file column description) and use that for import

**Comment by philippkraft** [comment]
## Idea for a)

xyz.conf
```
...
sample_parser = xyz-parser.yml
...
```

xyz-parser.yml, for a sample pattern like SiteName-123121-TOC
```
site:
   pattern: ^(\w+?)-
   output: \1
date:
  pattern: -([0-9\.]+?)-
  output: \1
  format: %d%m%y
site-map:
  SiteName: 87
  OtherSite: 93
```
